site_name: springboot
repo_name: mkdocs_springboot
repo_url: https://github.com/wumingsheng/mkdocs_springboot

remote_branch: gh-pages

copyright: 'Copyright &copy; 2019 Square, Inc.'

nav: 
  - Home: index.md
  - okhttp: okhttp.md
  - guava: guava.md
  - pipeline: autowired-2-list.md
  - springboot获取profile: springboot-profile.md
  - 自定义starter: self-define-starter.md
  - session共享: springboot-session.md
  - 读取配置文件: read-properties.md

# pip install mkdocs-material
theme:
  language: 'en'
  name: 'material'
  favicon: images/icon-square.png
  logo: images/icon-square.png
  palette:
    primary: 'teal'
    accent: 'white'


extra_css:
  - 'css/app.css'





# pip install pygments
# pip install pymdown-extensions
markdown_extensions:
  - admonition
  - smarty
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.critic
  - tables
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg


